### PR TITLE
Intorduce shmem

### PR DESCRIPTION
**Pull request by peterrum**
A first draft. Depends on https://github.com/dealii/dealii/pull/11290.

@kronbichler If this looks reasonable I will adjust the other BPs.

resolves #7

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
Nice.

**Comment by peterrum** [comment]
I have adjusted all BPs accordingly. Please note that I am creating the communicator only once (in `main()`). The reason for this is that creating new communicators at large scale (half machine runs on SuperMUC-NG) takes seconds up to ten seconds so that the  the parameters studies would too slow ;)

**Review by kronbichler — APPROVED** [review]
This looks good. The only thing one might be able to do differently is to construct the shared memory communicator inside the `do_test` function. This allows you to skip passing the `comm_shmem` into the 12 or so invocations for the precompiled degrees and still construct it only once per run. If you are happy with the present version, feel free to merge yourself.

**Comment by peterrum** [comment]
> The only thing one might be able to do differently is to construct the shared memory communicator inside the do_test function.

I'll make the change!

> If you are happy with the present version, feel free to merge yourself.

I don't have the rights to do this ;)

**Pull request merged**
